# Generated by Django 5.1.2 on 2024-10-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
