# Generated by Django 5.1.2 on 2024-10-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0002_alter_unidentifiedmissingperson_founded_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidentifiedmissingperson',
            old_name='founded_data',
            new_name='date_of_foundend',
        ),
    ]
