# Generated by Django 5.1.2 on 2024-10-16 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0002_volunteer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses_set', to='MissingPersonApp.volunteer'),
        ),
        migrations.AddField(
            model_name='contact',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_set', to='MissingPersonApp.volunteer'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Found Person', 'Found Person'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='addresses',
            field=models.ManyToManyField(related_name='volunteers_addresses', to='MissingPersonApp.address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contacts',
            field=models.ManyToManyField(related_name='volunteers_contacts', to='MissingPersonApp.contact'),
        ),
    ]
