# Generated by Django 5.1.2 on 2024-10-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0004_remove_address_volunteer_remove_contact_volunteer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='unidentifiedbody',
            name='contacts',
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='MissingPersonApp.address'),
        ),
        migrations.AddField(
            model_name='unidentifiedbody',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_bodies', to='MissingPersonApp.contact'),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='body_photo_upload',
            field=models.FileField(blank=True, null=True, upload_to='body_photos/'),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='dna_sample_collected',
            field=models.FileField(blank=True, help_text='Upload DNA samples collected', null=True, upload_to='dna_samples/'),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='fingerprints_collected',
            field=models.FileField(blank=True, help_text='Upload fingerprints collected', null=True, upload_to='fingerprints/'),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='fir_photo',
            field=models.FileField(blank=True, help_text='Upload the FIR document', null=True, upload_to='fir_photos/'),
        ),
        migrations.AlterField(
            model_name='unidentifiedbody',
            name='post_mortem_report_upload',
            field=models.FileField(blank=True, help_text='Upload the post-mortem report', null=True, upload_to='post_mortem_reports/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='MissingPersonApp.address'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='MissingPersonApp.contact'),
        ),
    ]
