# Generated by Django 5.1.2 on 2024-10-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0004_remove_unidentifiedmissingperson_date_of_foundend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedmissingperson',
            name='caste',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('SC', 'SC'), ('ST', 'ST')], max_length=50, null=True, verbose_name='Caste'),
        ),
    ]
