# Generated by Django 5.1.2 on 2024-10-17 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0005_remove_unidentifiedbody_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='contacts',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='missing_person_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person_addresses', to='MissingPersonApp.address'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='missing_person_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person_contacts', to='MissingPersonApp.contact'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reporting_person_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_person_addresses', to='MissingPersonApp.address'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='reporting_person_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_person_contacts', to='MissingPersonApp.contact'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='Missingperson_photos/'),
        ),
    ]
