# Generated by Django 5.1.2 on 2024-10-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0005_alter_unidentifiedmissingperson_caste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MissingPersonApp.missingperson'),
        ),
    ]
