# Generated by Django 5.1.2 on 2024-10-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0006_remove_missingperson_addresses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missingperson',
            old_name='missing_person_address',
            new_name='addresses',
        ),
        migrations.RenameField(
            model_name='missingperson',
            old_name='missing_person_contact',
            new_name='contacts',
        ),
    ]
