# Generated by Django 5.1.2 on 2024-10-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0007_rename_missing_person_address_missingperson_addresses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='reporting_person_address',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='reporting_person_contact',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='MissingPersonApp.address'),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missing_person', to='MissingPersonApp.contact'),
        ),
    ]
