# Generated by Django 5.1.2 on 2024-10-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0008_remove_missingperson_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Undefined Body', 'Undefined Body'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Undefined Body', 'Undefined Body'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
    ]
