# Generated by Django 5.1.2 on 2024-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0009_alter_address_type_alter_contact_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='access_to_vehicle',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='areas_regions_willing',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='details_of_previous_experience',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='method_of_reporting_progress',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='preferred_mode_of_search',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='specialized_skills',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='track_live_location',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='uploaded_evidence',
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='volunteered_in_similar_cases_before',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='contact_numbers',
            field=models.CharField(blank=True, help_text='Contact number(s) of the reporting person', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Email address of the reporting person', max_length=255, null=True),
        ),
    ]
