# Generated by Django 5.1.2 on 2024-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0010_remove_missingperson_access_to_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('division', models.CharField(blank=True, max_length=100, null=True)),
                ('police_station', models.CharField(max_length=100)),
                ('sub_division', models.CharField(blank=True, max_length=100, null=True)),
                ('chowkis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
