# Generated by Django 5.1.2 on 2024-10-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0011_hospitalentity_legalentity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalEntity',
        ),
        migrations.DeleteModel(
            name='LegalEntity',
        ),
    ]
