# Generated by Django 5.1.2 on 2024-10-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0013_division_zone_hospital_policestation_chowki_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='subtype',
            field=models.CharField(choices=[('Permanent Address', 'Permanent Address'), ('Current Address', 'Current Address'), ('Emergency', 'Emergency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Undefined Missing Person', 'Undefined Missing Person'), ('Undefined Body', 'Undefined Body'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subtype',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business'), ('Emergency', 'Emergency')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('Missing Person', 'Missing Person'), ('Undefined Missing Person', 'Undefined Missing Person'), ('Undefined Body', 'Undefined Body'), ('Volunteer', 'Volunteer')], max_length=50),
        ),
        migrations.CreateModel(
            name='UndefinedMissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age (Estimated)')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=50, null=True, verbose_name='Gender')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('complexion', models.CharField(blank=True, choices=[('Fair', 'Fair'), ('Dusky', 'Dusky'), ('Wheatish', 'Wheatish'), ('Dark', 'Dark')], max_length=50, null=True, verbose_name='Complexion')),
                ('hair_color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Brown', 'Brown'), ('Grey', 'Grey')], max_length=50, null=True, verbose_name='Hair Color')),
                ('hair_type', models.CharField(blank=True, choices=[('Straight', 'Straight'), ('Wavy', 'Wavy'), ('Curly', 'Curly'), ('Bald', 'Bald')], max_length=50, null=True, verbose_name='Hair Type')),
                ('eye_color', models.CharField(blank=True, choices=[('Dark brown', 'Dark brown'), ('Light Brown', 'Light Brown'), ('Hazel', 'Hazel'), ('Amber', 'Amber'), ('Green', 'Green'), ('Gray', 'Gray')], max_length=50, null=True, verbose_name='Eye Color')),
                ('distinctive_features', models.TextField(blank=True, null=True, verbose_name='Distinctive Features')),
                ('photo_upload', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo Upload')),
                ('caste', models.CharField(blank=True, choices=[('Open', 'Open'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], max_length=50, null=True, verbose_name='Caste')),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed')], max_length=50, null=True, verbose_name='Marital Status')),
                ('religion', models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Sikh', 'Sikh')], max_length=50, null=True, verbose_name='Religion')),
                ('other_known_languages', models.CharField(blank=True, choices=[('Hindi', 'Hindi'), ('Marathi', 'Marathi'), ('Bengali', 'Bengali')], max_length=255, null=True, verbose_name='Other Known Languages')),
                ('identification_details', models.TextField(blank=True, null=True, verbose_name='Identification Details')),
                ('last_location', models.TextField(blank=True, null=True, verbose_name='Last Location of Missing Person')),
                ('last_seen_details', models.TextField(blank=True, null=True, verbose_name='Last Seen Details/Sighting Details')),
                ('condition_at_discovery', models.CharField(blank=True, choices=[('Memory loss', 'Memory loss'), ('Shock', 'Shock'), ('Injured', 'Injured'), ('Other', 'Other')], max_length=50, null=True, verbose_name='Condition at Discovery')),
                ('reporting_person_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Reporting Person')),
                ('reporting_person_contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number(s)')),
                ('reporting_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('relationship_with_victim', models.CharField(blank=True, max_length=255, null=True, verbose_name='Relationship with Victim')),
                ('availability_for_search_operations', models.CharField(blank=True, max_length=50, null=True, verbose_name='Availability for Search Operations')),
                ('preferred_mode_of_communication', models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferred Mode of Communication')),
                ('access_to_vehicle', models.BooleanField(default=False, verbose_name='Access to Vehicle for Search Operations')),
                ('special_skills', models.TextField(blank=True, null=True, verbose_name='Special Skills')),
                ('previous_search_experience', models.TextField(blank=True, null=True, verbose_name='Details of Previous Search Experience')),
                ('upload_evidence', models.FileField(blank=True, null=True, upload_to='evidence/', verbose_name='Upload Evidence (e.g., photos, notes)')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='MissingPersonApp.address')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Undefined_missing_person', to='MissingPersonApp.contact')),
            ],
        ),
    ]
