# Generated by Django 5.1.2 on 2024-10-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0014_alter_address_subtype_alter_address_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undefinedmissingperson',
            name='age',
        ),
        migrations.AddField(
            model_name='undefinedmissingperson',
            name='estimated_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
