# Generated by Django 5.1.2 on 2024-10-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0015_remove_undefinedmissingperson_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='undefinedmissingperson',
            name='birth_mark',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
