# Generated by Django 5.1.2 on 2024-10-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0016_undefinedmissingperson_birth_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='undefinedmissingperson',
            old_name='distinctive_features',
            new_name='other_distinctive_mark',
        ),
    ]
