# Generated by Django 5.1.2 on 2024-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0017_rename_distinctive_features_undefinedmissingperson_other_distinctive_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedbody',
            name='last_seen_details',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
