# Generated by Django 5.1.2 on 2024-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0018_unidentifiedbody_last_seen_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='Condition',
            field=models.CharField(blank=True, choices=[('Memory loss', 'Memory loss'), ('Shock', 'Shock')], max_length=20, null=True),
        ),
    ]
