# Generated by Django 5.1.2 on 2024-10-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0019_missingperson_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='undefinedmissingperson',
            name='Condition',
            field=models.CharField(blank=True, choices=[('Memory loss', 'Memory loss'), ('Shock', 'Shock')], max_length=20, null=True),
        ),
    ]
