# Generated by Django 5.1.2 on 2024-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0020_undefinedmissingperson_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undefinedmissingperson',
            name='other_distinctive_mark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
