# Generated by Django 5.1.2 on 2024-10-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissingPersonApp', '0021_alter_undefinedmissingperson_other_distinctive_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField()),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MissingPersonApp.missingperson')),
                ('undefined_missing_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MissingPersonApp.undefinedmissingperson')),
                ('unidentified_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MissingPersonApp.unidentifiedbody')),
            ],
        ),
    ]
